services:
  app:
    entrypoint:
    - sleep
    - infinity
    # Uncomment build section below to build a fresh version of the image, uncomment image section to use a pre-built image
    # image: coder/python-dev-env:latest
    build:
      context: .
      target: builder
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

