FROM docker/dev-environments-default as builder

ARG ver=3.11.4

RUN apt update && apt upgrade -y
RUN apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev -y
RUN wget https://www.python.org/ftp/python/${ver}/Python-${ver}.tgz
RUN tar -xvf Python*.tgz
WORKDIR /Python-${ver}
RUN ./configure --prefix=/usr/local --enable-optimizations --enable-shared LDFLAGS="-Wl,-rpath /usr/local/lib"
RUN make altinstall
RUN ln -s -T /usr/local/bin/python3.11 /usr/local/bin/python3
RUN ln -s -T /usr/local/bin/pip3.11 /usr/local/bin/pip3
RUN ln -s -T /usr/local/bin/python3.11 /usr/local/bin/python
RUN ln -s -T /usr/local/bin/pip3.11 /usr/local/bin/pip
RUN python -m pip install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install --upgrade wheel
RUN pip3 install --upgrade virtualenv

WORKDIR /
RUN rm -rf /Python-${ver}
RUN rm Python*.tgz

RUN chsh -s /bin/zsh root
WORKDIR /root/.oh-my-zsh
RUN git pull
WORKDIR /root
COPY .docker_image_files/.zshrc .zshrc
COPY .docker_image_files/poshtheme.omp.json poshtheme.omp.json

RUN curl -s https://ohmyposh.dev/install.sh | bash -s

WORKDIR /com.docker.devenvironments.code/
COPY .vscode .vscode